version: "3.8"

services:
  django:
    container_name: django
    build: ./django
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./django:/usr/src/app
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - "8080:80"
