services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgresdjangoecs
  django:
    container_name: django
    image: test-django
    build: ./django
    volumes:
      - ./django:/usr/src/app
      - gunicorn-sock:/var/run/gunicorn
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgresdjangoecs
      - POSTGRES_PORT=5432
    command: |
      bash -c "python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn myapp.wsgi --bind=unix:/var/run/gunicorn/gunicorn.sock"
  nginx:
    container_name: nginx
    image: test-nginx
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - gunicorn-sock:/var/run/gunicorn
      - ./django/static:/usr/share/static
volumes:
  gunicorn-sock:
  postgres-data:
